### ISSUE TITLE
 Produced dump is "swapped" i.e. bootloader is at the end of flash

### ISSUE THREAD

**Issue by Yamacore** [openshwprojects/BK7231GUIFlashTool#11]
Hello there, i just did an dump as explained here: "https://github.com/tuya-cloudcutter/tuya-cloudcutter/issues/359"
And it seems the bootloader is at the end of flash.

**Comment by openshwprojects** [comment]
Thank you for reporting the problem, how did you managed to get swapped binary? We fixed it long, long time ago... which tool version do you have? Can you post a screenshot?

**Comment by Yamacore** [comment]
![dump](https://user-images.githubusercontent.com/20658441/233195185-161598b0-219b-4767-b810-4585bd365f88.PNG)
I used the "bk7231flasher_1.0.7.zip" the dumped file is uploaded in the cloudcutter issue i linked, maybe an error on my side?

**Comment by openshwprojects** [comment]
Thank you, it seems that one of the buttons was not updated. Everyone must be using the auto read and write so no one noticed yet.
Thanks!
