### ISSUE TITLE
Rewrite previously read original firmware

### ISSUE THREAD

**Issue by ipn00tic** [openshwprojects/BK7231GUIFlashTool#2]
Great program.
It was very interesting and I think it should be allowed to go back to the original firmware via dump.
The program makes the original dump but has no option to write the original dump in case something goes wrong.

thanks for the work

**Comment by openshwprojects** [comment]
Thanks, it's a good idea and it will be added soon, I think.

**Comment by openshwprojects** [comment]
Added, thanks!

**Comment by BenJamesAndo** [comment]
In case anyone is looking for this option, you have to click `Show advanced options`, then tick `Allow backup restore`. After that you should be able to select your Tuya backup .bin file in `Select firmware:`
The flasher tool looks in the backups folder. I was able to succesfully re-flash a Tuya firmware file.

![image](https://github.com/user-attachments/assets/6122e23d-cfb1-4b71-9870-d0150d3f3cae)
