### ISSUE TITLE
Silly question: OpenBK = Tasmota?

### ISSUE THREAD

**Issue by daxliniere** [openshwprojects/BK7231GUIFlashTool#37]
Sorry if this is a silly question, but is this firmware Tasmota specifically for BK7231-based devices?

Thanks in advance.

**Comment by openshwprojects** [comment]
it's like Tasmota and works with many Tasmota commands, but it's not Tasmota itself, it supports many, many chips

**Comment by daxliniere** [comment]
Thank you so much for your fast response!
