### ISSUE TITLE
"Do firmware write (no backup!)" does nothing

### ISSUE THREAD

**Issue by Suxsem** [openshwprojects/BK7231GUIFlashTool#4]
All buttons work except for "Do firmware write (no backup!)", can you please take a look?

**Comment by NielsPiersma** [comment]
I have the same issue. I can't "forcibly" overwrite my test boards. I tested for Both T and N boards.
Niels

**Comment by NielsPiersma** [comment]
First attempt 
Backup goes fine, flashing fails.
![image](https://user-images.githubusercontent.com/70269175/210998377-1b8d539a-83b0-4186-b4d4-bd5a8a3ae33d.png)

**Comment by NielsPiersma** [comment]
second attempt, with high baud-rate
![image](https://user-images.githubusercontent.com/70269175/210998527-209c2aca-a8f0-4484-b277-495cb5c28c6a.png)

**Comment by NielsPiersma** [comment]
and with higest baud rate
![image](https://user-images.githubusercontent.com/70269175/210998668-eb2af4e4-8b8d-4946-a827-52c3e0dcd1c4.png)
Will revert back too lower baud rate and test further

**Comment by NielsPiersma** [comment]
Test read/write (advanced option) works fine.
![image](https://user-images.githubusercontent.com/70269175/210998856-3d96d0d5-3c8d-4e64-9207-740761959102.png)

Did notice log screen doesn't resize.

**Comment by NielsPiersma** [comment]
And the last attempt for the N was successful. 
![image](https://user-images.githubusercontent.com/70269175/211000331-9435bb18-1cb4-47a3-991a-e143e41994ad.png)

Now will try the T version.
Niels

**Comment by openshwprojects** [comment]
I simply forget to link action to the button, will push a fix and release now. Thanks.

**Comment by openshwprojects** [comment]
https://github.com/openshwprojects/BK7231GUIFlashTool/commit/4e605dc3f314a29a9fc8573524e6b54ade5c54fb

**Comment by Suxsem** [comment]
Thank you!!!!
