### ISSUE TITLE
Improve firmware backup & restore process

### ISSUE THREAD

**Issue by HumbleDeer** [openshwprojects/BK7231GUIFlashTool#7]
Some tips for a smoother experience:

- After downloading the latest firmware from Github, automatically select it as the "Select firmware" file
- Highlight the latest firmware with a `(latest)` tag in the selection menu
- When doing a backup, prompt the user for a name, and use that name in the filename.
- After a successful read (and write), echo the location of the bin file to the user
- Change the firmware selection menu to include a table-based window where firmware files can be explored (eg read firmware files, openbk firmware files, details of files, etc) and selected as actively usable or deselect to hide it from the menu. (eg using [system.windows.forms.datagridview class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview)

**Comment by openshwprojects** [comment]
Thank you, we have added backup restore in last build.
